url: "http://restaurantgalia.com/"
baseurl: ''
title: Restaurant Galia
description: > 
   Diplômé de la haute école de cuisine française Grégoire Ferrandi, 
   le chef Maxim Godigna est le propriétaire du restaurant Galia, 
   123 rue Didot dans le 14ème (face au bâtiment de la Croix-Rouge française).
email: restaurantgalia@hotmail.com
timezone: Europe/Paris
keep_files: []
exclude:
  - _app
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - CNAME
  - template.zip
  - package.json
  - package-lock.json
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
