title: Restaurant Galia
email: restaurantgalia@hotmail.com
description: > 
   Diplômé de la haute école de cuisine française Grégoire Ferrandi, 
   le chef Maxim Godigna est le propriétaire du restaurant Galia, 
   123 rue Didot dans le 14ème (face au bâtiment de la Croix-Rouge française).
url: "http://restaurantgalia.com/"
markdown: kramdown
